using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class GridColumn : MonoBehaviour
{
    public RectTransform rect { get; private set; }

    protected GridController gridController;

    // Start is called before the first frame update
    void Start()
    {
        if (rect == null) rect = GetComponent<RectTransform>();

        if (gridController == null) gridController = GetComponentInParent<GridController>();
        if (gridController == null)
        {
            Debug.LogError("No GridController for this object. Columns should only be generated by a Grid");
            Destroy(gameObject);
        }
    }

    public virtual void SetHeight(float height)
    {
        if (gridController == null) gridController = GetComponentInParent<GridController>();
        if (rect == null) rect = GetComponent<RectTransform>();
        rect.SetSizeWithCurrentAnchors(RectTransform.Axis.Vertical, height);
    }
}
